## セットアップ手順（macOSを想定）
1. 使用中のPCでupdate.shを実行
1. 使用中のPCでiterm2の設定をファイルに保存
1. 新PCにiTerm2をブラウザからインストール
1. 新PCにhomebrewをインストール
1. homebrewを使用して、新PCにgitをインストール
1. githubのセットアップを行う（https://docs.github.com/en/get-started/quickstart/set-up-git）
1. gitを使用して、新PCに本リポジトリをclone
1. 新PCでsetup.shを実行
